### PR TITLE
Implemented compileJJTree task

### PR DESCRIPTION
**Pull request by maoueh**
This is an initial implementation of a JJTree task feature. Added tests which passes and tested on my project. I will make some more tests with some JavaCC only project to ensure they are still working great.

Once we agree that it's ok with you, I will update `README.md` file.

* It is now possible to compile a JJTree file to re-use it afterward
   in when compiling JavaCC.
* Test resources have been moved in two distinct directories: one
   for `javacc` and another one for `jjtree`.

Regards,
Matt

### CODE REVIEW

**Comment by maoueh** [comment]
Hi John,

I implemented the abstract common base task class and addressed lots of review comments.

Tests will fail right now as I wanted to add some syntactic sugar allowing this form of setting inputs/ouputs:

```
compileJavacc {
  inputDirectory('src/main/custom')
  outputDirectory('generated/files')
}
```

For now, I hit a knot for this as Gradle complains with the following message:

```
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method inputDirectory() for arguments [src/main/custom] on root project 'simpleJJTreeTestWithConfiguredInputsOutputs'.
```

Not sure yet how to solve this. Another thing I noted is potential erroneous logic when building the the output directory of an input file to compile. Check out the [FIXME](https://github.com/johnmartel/javaccPlugin/commit/d1b45d6cd3e2eb0d741a0b489f32099d4bd3f703#diff-280b537a65d077c6722cf0ae0be43f2bR144) I added for information on the problem.

Maybe you have some insights about these two problems.

Even with these problems still in, the PR is ready for another round of review.

Regards,
Matt

**Comment by johnmartel** [comment]
FYI I pulled at lunch time and I'm working on fixing the failing tests. I'm not sure about having the possibility to provide multiple input sources, since there is a single possible output directory. I will think about it...

**Comment by maoueh** [comment]
Maybe we could limit this possibility indeed. Problem is really when trying to compute the relative destination path inside the output directory. Having a single output directory with multiple sources is common and I'm personally against it, the java compile works like this if I remember correctly.

For the failing tests, maybe we can delay the "prettier" syntax in build file to an upcoming PR. What do you think?

**Comment by maoueh** [comment]
I removed changes to `build.gradle` in acceptance tests so they work again. Will work on user experience once we merge this one. If you worked on make it work already, don't throw it away, I could start from there the next time.

I have fixed the multiple sources compilation [in this commit](https://github.com/nuecho/javaccPlugin/commit/3e0defd5f8b87eb3fc20913b6814756203b4f8fe).

Also, I ran a full clean up all java source files using in Eclipse `Project > Source > Clean Up` using the project's clean up configuration. You can see the result in commit 81706d0](https://github.com/nuecho/javaccPlugin/commit/81706d071a1cf8a5df3938c85acb18d2fe57f461). I will probably remove this commit from the PR if you agree as clean up does not do the right thing in lot of cases, at least in my opinion :)

All tests were passing inside Eclipse, but they seem to fail when run via the command line. I will investigate this.

**Comment by johnmartel** [comment]
Tests were failing because they were running in parallel. Since tests are quite fast for now, I got back to running in serial mode. I didn't want to get into changing the output folder for each and every test for now. That's something we can improve later on. I'm proof-reading everything and then I'll merge your branch :)

**Comment by maoueh** [comment]
Nice :) Are you working on the readme? As I'm still open to make the necessary changes as well as renaming `JavaToJavaccDependencyAction` to something more meaningful now.

Ping me if you want me to do it.

**Comment by johnmartel** [comment]
I’m just releasing 2.1.0 with the updated README :) Then I’m off to bed. If you see matter for improvement, then by all means help yourself then submit a PR, but as I will be implementing JJDoc, don’t spend too much time, I will make some improvements and try to get the SourceTask syntax to work correctly so that we can get rid of the inputDirectory property.

Thanks again for a superb contribution!

**Pull request merged**
